name: sagas_meta
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Samlet Wu <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  path: ^1.4.1
  http: 0.12.0
  equatable: 0.1.6
  # rxdart: ^0.18.1
  rxdart: ^0.21.0
  dart_amqp: ^0.1.4
  # bloc: ^0.9.5
  bloc: ^0.11.0
  intl: ^0.16.0
  decimal: ^0.3.0
  sprintf: ^4.0.0

  # grpc
  async: '>=1.13.3 <3.0.0'
  grpc: ^1.0.0
  protobuf: ^0.13.4

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
